### ISSUE TITLE
Replace SHA256 with BLAKE2 everywhere

### ISSUE THREAD

**Issue by david415** [upspin/upspin#218]
Let's replace all instances of sha256 with blake2s or blake2b... or is there a reason not to?
Here's another modern crypto project, Zcash which is also considering this issue:
https://github.com/zcash/zcash/issues/706

**Comment by tarcieri** [comment]
It'd be nice if the BLAKE2 web site would update their numbers to reflect AVX2 implementations (*poke* @veorq), such as the one provided by Go.

Modern Intel CPUs now support SHA Extensions that natively implement SHA256 in hardware. SHA256 is also one of the algorithms most likely to be implemented in hardware on MCUs, although that does not seem to be terribly important to the Upspin use case.

BLAKE2 is neat and will probably outperform SHA256 in most cases provided you're using optimized implementations of both algorithms. But SHA256 is also fine.

**Comment by veorq** [comment]
Will update :)

**Comment by adg** [comment]
@david415 wrt this and issue #219, please provide more information. There's no way for me to evaluate your suggestions since you haven't provided any rationale for the changes.

**Comment by tarcieri** [comment]
@adg the tl;dr: rationale is BLAKE2 stands a fairly decent chance of being faster than SHA2 provided you're comparing optimized software implementations.

Given you've already shipped with SHA-256, there's probably not a whole lot of impetus to switch though. Go provides an AVX2-optimized SHA-256 implementation which should perform well.

**Comment by veorq** [comment]
Added to https://blake2.net/

![](https://blake2.net/haswell.png)

**Comment by n2vi** [comment]
Thank you for the suggestion and pointers.  I agree BLAKE2b looks like a
good choice, especially for applications with fewer long-term-compatibility
concerns or a well understood user base.    For Upspin, SHA-256 seemed to
me a safe, uncontroversial, widely inter-operable choice.

I've lived through the transition from MD5 to SHA1 to SHA-256, so it is not
that I expect our choice to be perfect forever.  And I knew today's SHA1
collisions announcement was coming.   I still have a Venti store at home
which works just fine, because it is read only and the hashes were computed
years before collisions were feasible.  That's the timescale on which an
archival file protocol needs to live, for me.

The consensus in the crypto community seems to be that SHA-256 is good
enough for now, but it is wise to be exploring the various replacements and
to be ready to make
a change.   When that time comes, I expect to use the dual signature fields
in DirEntry Packdata to ease the transition.

**Comment by tarcieri** [comment]
Yeah, SHA-256 is "good enough", and Go in particular has a nicely fast SHA-256 implementation. @veorq also published an updated version of the above graphs using implementations from SUPERCOP which paint SHA-256 in a better light:

![Graphs](https://pbs.twimg.com/media/C5XlF8hXAAMg30U.jpg)

**Comment by n2vi** [comment]
Closing for now;  re-open someday if it becomes a crucial matter.   There are indications that by then instruction sets may have changed enough to affect which BLAKE variant to select.
