### ISSUE TITLE
Protocol: Decouple email from username

### ISSUE THREAD

**Issue by skycafemix** [upspin/upspin#221]
Username should not be tied to actual email address for a plethora of reasons.
- Danger of spammers and other actors obtaining email adress
- Prevents anonymous posting
- Email addresses change, therefore must allow user to change the email address.
- Very difficult to manage multipke accounts. Have seen this problem with Dropbox when managing family's accounts.
- Difficult to automate if you require email to be picked up and analyzed.
- Email servers and transport not always secure

The second step is to receive an email message from the key server and to click the confirmation link that it contains. Visiting that link proves to the key server that you control the email address that you are registering and completes the signup process

**Comment by adg** [comment]
Email addresses are a central part of the system's design. Apologies if I come across as overly defensive, but here are some counterarguments to what you have here:

> Danger of spammers and other actors obtaining email adress

The email address need not be your personal address. It's just a unique identifier that you choose once. For instance, my practical Upspin user is `nf@wh3rd.net` but that's not the email address I usually go by. 

> Prevents anonymous posting

Anonymity is not a design goal of Upspin. At all. In fact, it's pretty much impossible to put any data in the system without signing it. But you can use a pseudonym; it's just a matter of signing up with an email address that has nothing to do with you.

> Email addresses change, therefore must allow user to change the email address.

The only time you need to actually use the address to receive email is when you sign up. After that you use your public key to authenticate with the key server and other Upspin services.

FWIW, my email address hasn't changed in 15 years. But as I said earlier, the email address needn't be the one you use every day. It just needs to be some unique address that you controlled at signup. After that it doesn't matter if it changes.

> Very difficult to manage multiple accounts. Have seen this problem with Dropbox when managing family's accounts.

Have you tried this with Upspin? It's actually pretty easy to manage multiple accounts. The development team has been doing it since day one.

> Email servers and transport not always secure

It only needs to be used, during signup, when you're watching what's going on. After that, nobody can use your email address to interact with Upspin at all. Maybe this should be spelled out more clearly in the security document. (@n2vi?) 

There is some discussion about using different identifiers as user names in issue #155.

**Comment by swetland** [comment]
> FWIW, my email address hasn't changed in 15 years. But as I said earlier, the email address needn't be the one you use every day. It just needs to be some unique address that you controlled at signup. After that it doesn't matter if it changes.

I'm in the same boat, but I know there are people out there who go through email addresses like water...

An interesting question: is the model such that once username has be reserved in the key server by proving control of an email address and installing a public key, that name is now permanently "owned" by whoever holds the private key (and should it be lost, can never be reclaimed in any way)?

There are some interesting interactions between such a model and a world where many (most?) people do not have long-term control of their email address, email addresses are potentially recycled, etc.

**Comment by adg** [comment]
>  is the model such that once username has be reserved in the key server by proving control of an email address and installing a public key, that name is now permanently "owned" by whoever holds the private key (and should it be lost, can never be reclaimed in any way)?

Right. That's the model.

**Comment by awly** [comment]
So, in case user looses their keys, but still has access to their email, is there anything in the security model that prevents the user from recovering ownership of their email (in the keyserver)?
Of course, this presumes loss of all data, but the same email verification mechanism used at signup could be used to overwrite the public key in keyserver with a newly-generated one?

**Comment by n2vi** [comment]
No, we don't want to allow that because it means an adversary with
temporary access to the email account, or even temporary ability to sniff
an unencrypted SMTP link, could substitute their own key and trick your
sharing friends into wrapping for them instead of you.

This has been a serious real-world problem in earlier systems that depend
purely on the ownership of an email account with providers that release
expired email addresses to new users.

The user really needs to save their keys.  Write down those secretseeds!

**Comment by awly** [comment]
Ack. Makes sense.
I think this fact should be emphasized in signup docs (right now they leave you with a single replica on your workstation). Many users will assume the possibility of account recovery (as all major web products trained them to expect).

**Comment by skycafemix** [comment]
Thank you for answering my concerns.
Since loss of secret = loss of data with no recourse, would it be possible to register more than one key, or another user who can also admin the account? A master key could be put in the bank vault.

**Comment by n2vi** [comment]
A reasonable precaution is to have two accounts and an Access file that
grants full rights to each.  That's not precisely what you're asking for
but close.

**Comment by webmaven** [comment]
> This has been a serious real-world problem in earlier systems that depend purely on the ownership of an email account with providers that release expired email addresses to new users.
> 
> The user really needs to save their keys.

OK, so what happens in the reverse situation, where I *do* have my key, but no longer have access to the email address (eg. I changed ISPs, the domain expired, etc.)?

For that matter, what is a user who has been issued a previously registered email address supposed to do? Do they have any recourse if the previous owner of that email address is now impersonating *them*?

**Comment by n2vi** [comment]
One needs access to the email account only once, at initial signup.  After
that, access to the email account is neither required nor useful. After
initial signup, Upspin depends entirely on your key pair.

If you lose the email account and someone else gets it, you do not suffer
any risk as far as Upspin is concerned.   The new owner is unable to sign
up in Upspin with that email.  You are still in control of files stored
under what is now someone else's email.  That's liable to lead to
confusion, so I recommend you move the files elsewhere, but it is up to you.

If someone take on an email address that was previously used by someone
else, Upspin will not play along.  I think that someone should get their
own new, unique email address to prevent confusion even in areas unrelated
to Upspin, but for sure they need to do so if they want to use Upspin.

**Comment by n2vi** [comment]
I realize we haven't totally addressed all the points in the original post, such as a slick and yet safe way to update rewrite pathnames when you change your email address.  With the latest documentation change, we've probably gone as far as we'll be able to for now.
