### ISSUE TITLE
cloud/storage: implement AWS S3 storage backend

### ISSUE THREAD

**Issue by adg** [upspin/upspin#225]
It'd be nice if people could use Amazon S3 instead of Google Cloud Storage, if that's what they prefer.

**Comment by fawick** [comment]
I think it would be nice to be able to alternatively use [Minio](https://www.minio.io/), too. I do not now if its MIT license would allow for reusing some part of its Go code in Upspin. 

Now that I come to think of it: Wouldn't it be great to support all the storage systems that [Rclone](http://rclone.org/) offers? Again, I did not yet check whether the license (Apache 2.0 for rclone) allow code reuse in Upspin.

**Comment by DavidVorick** [comment]
I would also like to propose [Sia](https://github.com/NebulousLabs/Sia) as a potential storage backend - it's a decentralized cloud with no single points of failure, and it's also a lot cheaper than other cloud options.

**Comment by adg** [comment]
Please feel free to work on backends for those storage systems.

My only request is that each storage backend doesn't add a huge raft of
dependencies to the tree. I'm pretty unhappy about the dependencies that
the google cloud storage package brings in.

**Comment by robpike** [comment]
It should be possible to write storage systems in external repos. I believe the blocker is linking them into the server binary, but that is surmountable by forking the Upspin repo (ugh), and maybe soon by using  the embryonic plugin mechanism in Go 1.8. I think that the plugin model should be the way to go once it's possible.

**Comment by DavidVorick** [comment]
@robpike something I've seen work in other projects is having an HTTP or RPC interface with a bunch of endpoints that the external storage needs to implement, then the external storage writes some wrapper code to meet the interface, then you can just point upspin to the wrapper.

**Comment by wendel841** [comment]
+1 for this possibility or some abstraction to implement other cloud storage into upsin by users.

**Comment by fawick** [comment]
@wendel841 The abstraction is already there: Implementing the [`Storage` interface](https://godoc.org/upspin.io/cloud/storage#Storage) is all that's needed.
The GCS implementation is a good blueprint https://github.com/upspin/upspin/tree/master/cloud/storage/gcs.

And since today, [there is a S3 implementation ready for review](https://upspin-review.googlesource.com/c/8029/) as another blueprint.

As a matter of fact, I started working on a `Storage` implementation for B2 Cloud Storage and it is less difficult than I initially assumed.

**Comment by robpike** [comment]
Throughout the project the focus has been on the interfaces like DirServer and Storage, keeping them as simple as possible, so that other components can be added. An S3 storage implementation is just the kind of thing we'd like to see, along with more DirServers and StoreServers with unusual properties.

As we tried to stress during the release, Upspin is a framework, an approach, not fundamentally an implementation.

**Comment by adg** [comment]
wrt [this comment](https://github.com/upspin/upspin/issues/225#issuecomment-282423880) by @DavidVorick:

> something I've seen work in other projects is having an HTTP or RPC interface with a bunch of endpoints that the external storage needs to implement, then the external storage writes some wrapper code to meet the interface, then you can just point upspin to the wrapper.

One could write a `storage.Storage` implementation that makes HTTP requests to a separate storage backend binary.

**Comment by adg** [comment]
We have now completed the work to abstract the Google Cloud Platform-related code from the Upspin core. The work can be found in https://github.com/upspin/gcp. There is an aws repo that should contain code of a similar structure for working with AWS.
