### ISSUE TITLE
usability: "all" ACL has some rough edges

### ISSUE THREAD

**Issue by swetland** [upspin/upspin#230]
The fact that "all" accessible files are stored unencrypted makes sense when you think about the model but was not clear to me from reading the "Access Control" documentation.

The side-effect / protective feature that you cannot add an "all" ACL to an Access file if there are any other files in the directory also makes sense thinking about it after the fact but was perplexing when I first encountered it.  I created  user@example.com/public, put some stuff in there and then tried to add an Access file with read:all, list:all:

upspin: cp: user@example.com/public/Access: client.Put: cannot add "read:all" permission to existing files

Off the top of my head a significantly better model does not come to mind, but the docs should probably be a bit more emphatic about the limitations of "all" at a minimum.

Also, the docs say "As a side note: a user-name wildcard such as *@example.com applied to the read right can only provide genuine read access if the item being read is not encrypted, or if every user in the domain has a key wrapped for the item (see the Upspin Security document), which is impractical at best."

Which I *think* intends to say "if you intentionally store an item unencrypted, you can share it with *@example.com", but maybe means "we're not supporting *@example.com because it's complicated"?

**Comment by adg** [comment]
I have some thoughts about how to improve some of this.

Currently, when writing a file, if the special `all` user is among the readers, the client switches to use packing `eeintegrity` instead of the usual `ee`. (The `eeintegrity` packing stores the file unencrypted, and uses the directory entry packdata to store a checksum of its contents, to verify to any readers that the file was successfully read as written by the stated writer.)

There are a couple of downsides to this approach (which @swetland mentioned above, but I will restate them here for clarity):

- If you want to switch from public (`read:all`) to non-public (`read:someone@example.com`), or vice versa, you need to re-pack the file, which includes re-writing the contents to the store. Note that this is a different process to merely changing read permissions from one set of (non-`all`) users to another, which does not involve re-packing the files or re-writing their contents.
- `eeintegrity`-packed files are stored in plain text on the store server, giving the store owner and anyone that guesses the object Reference, unfettered access to the files. This is not a concern for files that are shared with `all` and stay that way, but if you later decide that you want to make a public file private, those plain text files remain on the store server (at least until we have some form of garbage collection).

My proposed change:

Move the `read:all` special case from the client to the `ee` packer, and therefore use `ee` packing for files with access `read:all`. In other words, the `ee` packer should recognize the user `all` as a special case, and in that case it should store the AES key (the one that is used to encrypt the file contents) *unwrapped* in the directory entry's packdata.

The upshot:

- File contents are encrypted on the store server, even if they are shared publicly.
- Switching from public to private, or vice versa, does not require a re-pack/write of the file contents. (It is the same modifying the set of readers in any other way, ie `upspin share`.)
- The client doesn't need to give the `read:all` case any special treatment. It just uses `ee` packing regardless.

I think this change is strictly better than the status quo. I also believe the change would be fully backward-compatible with any existing files. (Users would need to upgrade their clients to read public files written with the updated `ee` packing, though.)

@n2vi what do you think of this idea?

**Comment by n2vi** [comment]
It is a reasonable change.

As a practical matter, I'm not yet seeing any of us run directory servers
that are better hardened than store servers, though I hope to get to that
state someday.  In the meantime, the hoped-for protection against malicious
or compromised servers is a bit illusory.  The "all" decryption key will
live forever on directory server backup tapes.  Your more immediately
compelling argument is efficiency of moving a file from public to private,
and maybe that is enough by itself.

I don't have a good sense yet of how often I want to move public to
private.  When correcting a mistaken Access file, I would really like to
have a directory server access log that lists everyone who took advantage
of the wrong settings before I corrected them.  (This was a valuable
selling point for Google Apps against classic enterprise storage, though
only partly available to an ordinary end user.)  That feature would be more
valuable to me than re-pack efficiency.

When plain pack was introduced, I recall someone arguing that we should
have a mode for reading file content with very simple code that works even
if Upspin's code were hard to run.  Imagine an IoT platform without Go, for
example.

Would we keep around plain and eeintegrity after this change?  They'd be
almost unused.

**Comment by adg** [comment]
> Would we keep around plain and eeintegrity after this change?  They'd be almost unused.

Maybe? I'd have to think about it more.

**Comment by adg** [comment]
> As a practical matter, I'm not yet seeing any of us run directory servers that are better hardened than store servers, though I hope to get to that state someday.

I run my `upspinserver` on a private server that I control, but all my actual storage is in Google Cloud Storage. I feel like my DirServer is more secure than the contents of my StoreServer, in the sense that my StoreServer data is accessible by Google employees (although I do trust they won't look at it).

> I don't have a good sense yet of how often I want to move public to private.

The main "gotcha" that this helps with is accidentally writing something sensitive to a public directory. At least with the proposed change, the data will never be written unencrypted to a store.

**Comment by n2vi** [comment]
>
> I run my upspinserver on a private server that I control, but all my
> actual storage is in Google Cloud Storage. I feel like my DirServer is more
> secure than the contents of my StoreServer, in the sense that my
> StoreServer data is accessible by Google employees (although I do trust
> they won't look at it).
>

Excellent!   I stand corrected and agree that your proposed change helps.
