### ISSUE TITLE
feature request: pub/sub

### ISSUE THREAD

**Issue by mafik** [upspin/upspin#236]
Publish-subscribe pattern is an important feature of many filesystems / databases / social networks. Upspin should have it as well.

Example applications:
- notifications for new photos added to shared albums
- notifications for new blog posts from followed people
- live mirroring of storage server
- triggering a build when a source file is updated

**Comment by awly** [comment]
There's already a Watch RPC on dirserver: https://github.com/upspin/upspin/blob/2b715455079b29faa1fc1c9a1afd941e9d0471ef/upspin/proto/upspin.proto#L184

Although it could be better documented and exposed via upspin CLI.
It's also not clear if it emits events only on directory content changes (adding/removing files) or on file content changes as well.

**Comment by edpin** [comment]
Hi Andrew and Marek,

Yes, Watch (https://godoc.org/upspin.io/upspin#DirServer) is the interface for that. It gets updated whenever a new DirEntry is updated. But since files are immutable, DirEntries are changed when a file is "changed" because its References (inside the DirEntry's DirBlocks) are updated.
