### ISSUE TITLE
cmd/upspinfs: fakes writes to read-only files

### ISSUE THREAD

**Issue by masiulaniec** [upspin/upspin#282]
`upspin put` rejects the write as expected:
```
$ echo w:ann@example.com | upspin put nf@wh3rd.net/pub/Access
upspin: put: dir/remote.Put("remote,upspin.adg.tech:443"): invalid operation:
	dir/server.Put:
	user nf@wh3rd.net: writer of Access file does not match owner
$
```

But `upspinfs` fakes a write success:
```
$ echo w:ann@example.com >/u/nf@wh3rd.net/pub/Access
$ cat /u/nf@wh3rd.net/pub/Access
w:ann@example.com
$
```

**Comment by robpike** [comment]
I suspect this is the writeback cache lying to you, but I don't know for a fact. The file looks right to me now. Did you restore it?

**Comment by masiulaniec** [comment]
The previous content was made visible by restarting `upspinfs`. I didn't need to issue additional writes.

**Comment by presotto** [comment]
I'm totally confused.  I'll see if I can recreate somehow.  The writeback cache is only writeback for blocks.  The DirServer Put is synchronous.  It should be reporting exactly what happened.

Ditto for upspinfs.  It is paranoid enough to try writing the file as soon as you create it just to see if it will error out when if finally writes back when you close.

Smells like a bug to me.

**Comment by presotto** [comment]
Were you running a cacheserver?  The answer limits the number of things I have to bang my head against.  Thanks much.

**Comment by edpin** [comment]
It also matter whether adg.tech was running pre-CL/8024 (
https://upspin-review.googlesource.com/c/8024/).

**Comment by adg** [comment]
On 28 February 2017 at 07:25, Eduardo Pinheiro <notifications@github.com>
wrote:

> It also matter whether adg.tech was running pre-CL/8024 (
> https://upspin-review.googlesource.com/c/8024/).
>

If the attempt was made at around the same time as this issue report, then
yes upspin.adg.tech was running with that change.

**Comment by presotto** [comment]
I'm not succeeding in reproducing.  What flavor OS were you on?

**Comment by presotto** [comment]
I reroduced, sort of.  On Linux with a cacheserver and upspinfs I managed to write an access file in upspinfs with no error.  The access file didn't change (not even the view through upspinfs) but the write in upspinfs didn't return with an error.  Investigating.

**Comment by masiulaniec** [comment]
> What flavor OS were you on?

OSX 10.12.3, FUSE 3.5.5, upspin e9d5c942056f4b33e33aa6689efdc28b1e58f8e2

**Comment by presotto** [comment]
I've figured out the Linux version, hopefully the MacOS is the same.  I'll try that next.  On Linux, it doesn't report an error but also doesn't write the file, i.e., the error doesn't happen till I see a Flush whose error FUSE doesn't pass back to the client process.  Seeing if I can fix it somehow.

If you had just been creating the access for the first time you would have seen an error since on Create I first write a zero length file to see if subsequent writes will succeed at all.  Even that's a bit iffy to do but I figure its worth the effort since it doesn't really defy Posix semantics.  However, with a preexisting file, the kernel (and FUSE) just do a writeonly open and truncating the file would be wrong.  I guess I could do a WhichAccess and then a run my own check to see if it is writable.  I may have to do that.
