### ISSUE TITLE
cmd/upspinfs: make all symlinks relative

### ISSUE THREAD

**Issue by masiulaniec** [upspin/upspin#291]
Symlink target appears to always be an absolute path:

```
$ cd /u/$account/tmp
$ ln -s a b
$ [ $(readlink b) = "/u/$account/tmp/a" ] && echo path is absolute
path is absolute
$
```

So the fuse mount point, a local configuration detail, is leaking into the namespace. I worry that it puts unnecessary burden on tools such as `tar` or `rsync` to convert these symlinks into a relative form.

**Comment by presotto** [comment]
You are right.  Since we are using our own links to emulate linux/unix symbolic links there is not really a 1 to 1 correspondence.  We only have absolute links so there's no way to represent a relative link. The trade off was between making symbolic links from either world work in the other vs representing relative links specially in upspinfs using some escape like the ._ files FUSE uses to represent xattrs.  I chose the former. It does put the onus on users to use -h in tar.

**Comment by presotto** [comment]
Of course, another alternative is for upspinfs to return a relative link when it can and an absolute link otherwise while still maintaining an absolute link in upspinfs.  That might be the closest to what *nix users would want.  More exactly, if the link target is in the same user root as the link itself return a relative link and otherwise an absolute one.  Comments?

**Comment by presotto** [comment]
I'm being an idiot.  There's no reason they can't all be relative that I can think of.  CL coming.

**Comment by robpike** [comment]
I think this can be closed now. Reopen if you disagree.
