### ISSUE TITLE
key/remote: don't authenticate when querying keyserver

### ISSUE THREAD

**Issue by adg** [upspin/upspin#310]
The `KeyServer` doesn't validate authentication tokens when serving `KeyServer.Lookup` requests, so the `key/remote.Lookup` method shouldn't send them. This reduces the amount of knowledge that the `KeyServer` has about who is looking up which keys.

This will require some work on the client part of [package rpc](https://godoc.org/upspin.io/rpc). We should consider splitting the `Client.Invoke` method into two methods (`InvokeMethod` and `InvokeStream`) or three methods (`InvokeMethod`, `InvokeUnauthenticatedMethod`, and `InvokeStream`).

**Comment by edpin** [comment]
I'll take a stab at this. 

High-level plan is as @adg described with three different Invoke methods. 

However, I'd like to propose we take it a step further and make `rpc.Client` take a (possibly modified) `rpc.Service` object so that Servers and Clients are in sync. Meaning, if the Server uses a Service with an Authenticated method called `"/key/Put"` then we want the Client to also take that Service definition and have `"/key/Put"` implement a `InvokeAuthenticated` method.

This will require possibly three steps: 1) clean up the auth retry loop, 2) split Invoke into three, 3) make clients be more in sync with Servers as described above.

The first two steps are part of this issue. The third one might be best as another issue, which I will file soon.
