### ISSUE TITLE
upspin: provide API for Watch to return current order

### ISSUE THREAD

**Issue by robpike** [upspin/upspin#345]
This would provide the missing piece to use Watch(-1) to recover the full state of the tree.

**Comment by edpin** [comment]
I originally proposed a special value (-2?) to get only new state going forward. But Dave sort of convinced me that the few use cases I was thinking of were actually not very good.

We could use a special code to get the current order, so no new API would be necessary. The Events channel would be closed after the most current Event is sent on it.

However, what's the use case you have in mind? How would would it help you decide what to do any more than getting all future events?

**Comment by robpike** [comment]
I was seeing this as a way to get a clean copy of the tree, although I suppose it's easy enough to write a recursive tree walk. The difference is that with Watch there is a distinct point that marks the end of the traversal, which is when we reach the order sequence we started at. With a recursive walk in an active tree, it's never clear when to stop.

The use case may be small, but it does seem odd to me that we have this counter (the order) but no way to discover it.

**Comment by edpin** [comment]
I see. Perhaps Watch() could return the current Order as one of its returned values. It always means "the highest Order we currently know". If the tree doesn't change, that order number marks the (temporary) end of the event stream from Watch(-1). And if you Watch(0) or some other number, you know when the "last" event is for a while.

**Comment by robpike** [comment]
Closing as the use case isn't compelling enough.

**Comment by derekchiang** [comment]
Could we re-open this issue?  I'm building an application on Upspin and I need a way to receive only new events.  The reason why I don't want to use `Watch(0)` to discover the current order is that I can have a potentially very large number of files under the watch path, so `Watch(0)` would return way too much data.

**Comment by derekchiang** [comment]
I submitted [a patch](https://upspin-review.googlesource.com/c/9181/) that addresses my use case (namely, to only watch for new events).  It uses a special code `-2` as proposed by @edpin originally.  I did not include `fix #345` in the commit message as I was unsure whether the patch fully addresses this issue, since what @robpike wanted was a way to return the current order.

**Comment by derekchiang** [comment]
@adg [wanted to](https://upspin-review.googlesource.com/c/9181/#message-636a1bc83ce51c38206223449c1c7b1caac8d75a) know what kind of applications are interested in only new events.

In my case, I'm building a messaging application on Upspin, where messages are stored as plain files.  When a user opens the application, only the most recent messages are downloaded.  Then, the application needs to receive new messages via a `Watch` stream.  However, without a way to discover the current `order`, or to only receive new events, `Watch` will have to stream all messages, which is non-ideal since there can potentially be a very large number of messages.

**Comment by derekchiang** [comment]
@adg any updates?

**Comment by adg** [comment]
@derekchiang we talked about it today and I think it is fine to go in as proposed. I'll leave some comments on your change.

**Comment by derekchiang** [comment]
@robpike can we close this issue now that we've added `WatchNew` in [this patch](https://upspin-review.googlesource.com/c/9181/), or do you still want a way to discover the current order?

**Comment by robpike** [comment]
WatchNew is not the solution to the original question. Please leave the issue open.

**Comment by adg** [comment]
Will be resolved by #444.
