### ISSUE TITLE
upspin: improve new user and server setup process

### ISSUE THREAD

**Issue by adg** [upspin/upspin#411]
Right now, setting up a user and a server requires you to perform this somewhat confusing sequence of tasks:

1. run `upspin signup`
1. run `upspin setupdomain`
1. set a dns TXT record
1. run `upspin setupstorage-gcp`
1. create and configure a VM and put upspinserver on it
1. run `upspin setupserver`

Instead of this, I propose we create a command `upspin setup` (name unimportant) that starts a web server and opens the local browser to a web form:

```
User name:                        _______________ (an email address you own)
Server hostname:                  _______________ (the host name you wish to use for your Upspin instance)
Google Cloud Project name:        _______________
Google Cloud Storage Bucket name: _______________ (autofills to ${project}-upspin)
Google Compute Engine VM name:    upspinserver___

[Create]
```

When you click `Create`, the local setup server redirects you to fetch OAuth credentials from Google Cloud. After authorizing the app, you are redirected back to the local setup server, which sets everything up for you. All you need to do is click the 'verify' link in the signup email and create an DNS record for the server hostname.

The local setup server then does these things for you:

1. Generates keys and sends a signup request for the given user name (`user@example.com`).
1. Enables the relevant APIs in your Google Cloud Project.
1. Creates the named storage bucket (equivalent to today's `upspin-setupstorage-gcp`.
1. Creates the VM (running a Docker image preloaded with upspinserver).
1. Waits for these two conditions:
    - The presence of the user on the public key server. (Indicates that the user completed the signup process by clicking the link in the verification email.)
    - The resolvability of the given server hostname, and the accessibility of the unconfigured `upspinserver` at that host.
1. Generates keys for `user+server@example.com`, which is the user that the `upspinserver` will run as, and puts the key to the key server. (The`+snapshot` suffix avoids the need for the TXT record to prove domain ownership.)
1. Transfers the keys and configuration to the unconfigured `upspinserver` and makes the user's root (equivalent to today's `upspin-setupserver`).

If anything goes wrong at any of these stages, it should be straightforward to offer the user suggestions as to how to resolve things. (At least much easier than how it is now, spread across several different binaries.)

---

Blocking issue(s) include #239 (todo: add more relevant issues).

This signup process could be part the web UI proposed by #410.

Questions? Further thoughts? Criticisms? I know @edpin has also been thinking about this. It'd be great to try and nut out the design here in this issue.

**Comment by edpin** [comment]
This is what I'm working on and the flow is pretty much as I described in the meeting, which the above description captures well. 

Two things that need to be done differently though are the following:

1. **Support for multiple users**
2. **Ability to create users without domain names or servers in mind**

For 1), I plan on using a directory structure similar to what many in the team already use to support their multiple users and consistent with registering a new domain:

```
$HOMEDIR/upspin/<username>/config
```

For example, one could have three users:

```
/home/me/upspin/me@example.com/config
/home/me/upspin/test@example.com/config
/home/me/upspin/upspin@example.com/config
```
and use the `<username>` subdirectory to store keys, such that the config file would look like:

```
username: me@example.com
secrets: /home/me/upspin/me@example.com/
```

For 2), one of the idiosyncrasies of `cmd/upspin signup` is that one has to have a domain name in mind even before having a user. So, in the current installer tool I'm building, the first step is to pick a username and register it with the keyserver, without creating a fully-populated `config` file. The config file shown above contains only `username` and `secrets` and that's enough to register with the keyserver (by calling behind the scenes `upspin -config=/home/me/upspin/me@example.com/config signup -signuponly`. But of course, in the final implementation, there will be no need to invoke a binary, just simply perform the key and user registration and then in subsequent steps append the store and dir servers to the config file).

Sounds good so far?

**Comment by adg** [comment]
For 1, I proposed using a suffixed user (`user+server@example.com`) for the server user. What do you think about that?

That directory structure for multiple users sounds fine, though, although presumably their primary user will still be in `$HOME/upspin/config`?

**Comment by edpin** [comment]
Suffixed user is okay for server.  However, we should create new keys automatically and warn users that re-using the same user keys would weaken their server's security significantly. There should also be a way to select a new user entirely for server user, since suffixed users can always `key.Put` new keys and the main user account could accidentally/maliciously be used to put a compromised set of keys as the server's key. The paranoid might want that extra level of assurance. @n2vi for comments.

The primary user can be the soft link (in platforms that support it) to `$HOME/upspin/config` and if not supported, a hard link will have to do it. If no linking is supported, then maybe a copy and a warning.

**Comment by edpin** [comment]
Also, the suffix should be `+<domain>`, no? In case one has multiple domains and the user's own domain is not the same.

For example, I can be `dude@gmail.com` and control `example.com`. My server's user would be `dude+example.com@gmail.com`.

WDYT?

**Comment by n2vi** [comment]
Since I'm explicitly asked, my views are the following.  But I'm not doing
the work and can live with whatever y'all want.


Simplified setup should not involve servers and domains at all.  Newbies
should use a service such as jn.gl run by a pro.

Server username should default to upspin@{domain} but be easily overridden,
e.g. as required by local organization policy.

The biggest catastrophe is losing keys, either having them wiped out or
having them quietly stolen directly or off backup copies.  Having an ornate
structure mixing secrets and public information is more prone to this.
Frequent re-design of the conventions also leads to mistakes, so whatever
we change to this round ought to be the last change.

On Wed, Jul 12, 2017 at 11:27 AM, Eduardo Pinheiro <notifications@github.com

**Comment by adg** [comment]
> Suffixed user is okay for server.

That's what I'm proposing. You say it's "okay" but doe that mean that you want to go in this direction? This removes the necessity to set up a TXT record for a domain.

> However, we should create new keys automatically and warn users that re-using the same user keys would weaken their server's security significantly.

Of course, each user must have a unique key pair. We should never re-use the same key pair for different users, even suffixed ones.

> There should also be a way to select a new user entirely for server user, 

Agree that this should be possible, but should we make it part of the easy setup process? I think we have to make some decisions on the part of the user for this to work. The fewer variations we support the easier it will be to get this right.

> since suffixed users can always key.Put new keys and the main user account could accidentally/maliciously be used to put a compromised set of keys as the server's key.

What are the actual security implications here? If someone has your primary user key pair then they already have all your data, right? Seems like game over to me. @n2vi can you please comment on this concern? (I think this is why @edpin called your attention to this thread.)

> The primary user can be the soft link (in platforms that support it) $HOME/upspin/config and if not supported, a hard link will have to do it. If no linking is supported, then maybe a copy and a warning.

For the primary user, what is the rationale for deviating from our established defaults? I think the config should be in `$HOME/upspin/config` and the keys in `$HOME/.ssh` until we make an executive decision to change that default. The cost of change, even at this pretty early stage, is high.

> Also, the suffix should be +<domain>, no? In case one has multiple domains and the user's own domain is not the same.

I suggested a default suffix of 'upspin' or 'upspinserver' because 'domain' doesn't really mean anything in this context anymore. Your server will have a *hostname* but we shouldn't ask users to dedicate a *domain name* to their Upspin installation. Of course, the server user name can just be a pre-populated text input box that the user can change if they want to use a different user name.

**Comment by n2vi** [comment]
since suffixed users can always key.Put new keys and the main user account
could accidentally/maliciously be used to put a compromised set of keys as
the server's key.

What are the actual security implications here? If someone has your primary
user key pair then they already have all your data, right? Seems like game
over to me. @n2vi <https://github.com/n2vi> can you please comment on this
concern? (I think this is why @edpin <https://github.com/edpin> called your
attention to this thread.)


If someone gets the key for grosse@gmail.com, then they can read /
overwrite all my files on my server n2vi.org.  If they get the key for
server owner upspin@n2vi.org, then they can erase my wife's data as well.
So the two are both bad, nearly "game over", but not quite identical.    If
the key for upspin@n2vi.org​ becomes subordinate to grosse@gmail.com in
some way through suffix or whatever, there is a (modest) security hit.  I
think that's what @edpin was referring to.

It seems unwise to tie the server user to an ordinary user account, but I
can always work around this by creating an "adminstrator" account I only
use for service matters and keep grosse@gmail.com for ordinary use.   That
way, when I decide to hand off administration of the server to my daughter
in a decade or whatever, it is quite clear what is going on.

**Comment by robpike** [comment]
I am convinced that although expert users may wish to keep their keys near their configs, the default should certainly not do that, storing the keys under .ssh instead. Although that spreads the user's information around, and can be error-prone, for most purposes it is safer and more secure, building on the established convention of .ssh being protected.

In short, let's leave the structure of keys and configs alone. It's fine:
    $HOME/upspin/config
    $HOME/.ssh/{secret,public}.upspinkey

**Comment by robpike** [comment]
Is it possible to automate DNS setup, at least for some known registrars? It's a bump in the road when the user reaches that point in the process.

**Comment by adg** [comment]
It is possible, but it's also not even necessary to have a host name for your Store/Dir servers. One could just use the IP address.

**Comment by robpike** [comment]
That suggests a way to smooth the setup: Use the IP address and once it's all working, tell them what to do to make it a domain name.

**Comment by presotto** [comment]
I've never been thrilled with the necessity of  the TXT record for domains like mine where I am the only user.   Even if I were not, my wife would probably use here gmail.com account and not some new closedmind.org  in order to use my closedmind.org domain so being able to Put users in my domain is not that useful.

Given that, I'm happy to take the added weakness of using a suffixed name for the server. Given that as presotto@gmail.com I may want to manage multiple instances in different domain, i agree with eduardo that the suffix has to be unique.  Not sure about using the domain name since, as adg says, we don't necessarily need have to have one.  Perhaps the host name/address or a random number.

Some people (e.g. grosse) might want more control and for them we can add an <advanced> menu like settings in chrome where they can specify everything.

All that said, I'm happy with adg's original premise here, regardless of who implements it.

**Comment by adg** [comment]
Status update:

The [browser](https://godoc.org/exp.upspin.io/cmd/browser/) now supports deploying `upspinserver` to a Google Cloud Platform Compute instance, storing its content in a Cloud Storage bucket. The process is pretty similar to the description in the first comment, although there are more explicit steps. (It turned out that trying to cram everything into as few steps as possible made it more confusing.)

The compute instance runs a Docker image that runs an `upspinserver`. (see issue #239) That image is available publicly as `gcr.io/upspin-containers/upspinserver`, and is prepared by [upspin-deploy-gcp](https://godoc.org/gcp.upspin.io/cmd/upspin-deploy-gcp/).  A nice feature of using a Docker image is that for a user to update their `upspinserver` they can just click the 'restart' button on the instance in the cloud console.

As it stands, an Upspin team member needs to manually update the Docker image when required, but I'm now thinking about the best way to automate this.

I hope to solicit some testers for this feature soon. (And there's nothing stopping anyone from trying it now, if they like.)

**Comment by adg** [comment]
We've tested and now rolled out upspin-ui as part of the binary downloads, and updated the documentation to suggest this as the path for setting up. That means we're done with this issue. Woohoo!

**Comment by SCKelemen** [comment]
Is it still a goal to automate the TXT records for common registrars?

**Comment by adg** [comment]
@SCKelemen while it might be useful, it also seems like something that wouldn't be used by many of our users and that would also atrophy as the various registrars change their APIs and procedures. So I think it's probably not something we want to do.
