### ISSUE TITLE
config: choose a more sensible default path for secret 

### ISSUE THREAD

**Issue by adg** [upspin/upspin#437]
At present, if a config does not provide a `secrets:` field the default is to use `$HOME/.ssh`.

There are two separate issues with this:

1. `$HOME/.ssh` may not be the right default path.
2. The default path does not include the username, so that if you have multiple users on one system you must specify a `secrets:` field in the config of all users beyond the first.

I'm not too bothered by issue 1 at the moment. `$HOME/.ssh` seems like a reasonable place on Unix systems, as users that commit their dotfiles to a Git repo are likely to have `.ssh` in their `.gitignore` (this was the original rationale for choosing that location).

Issue 2 is the one I'd like to discuss here.

In @edpin's [installer CL](https://upspin-review.googlesource.com/c/11220/1/cmd/installer/pickuser.go#83) he proposes storing secrets in `$HOME/upspin/$USERNAME`. In this issue I propose we canonicalize this behavior, but instead use `$HOME/.ssh/$USERNAME`.

So, if a user were to `upspin signup` as `user@example.com` their keys would be written to `$HOME/.ssh/user@example.com`. Seems simple enough.

The remaining question is one of backward compatibility. Ideas about how to handle this:

1. If keys are not found in `$HOME/.ssh/$USERNAME` then `config` could default to reading them from `$HOME/.ssh`. This would prevent interruption of service, but effectively having two default locations it could also lead to confusing situations. For example: what happens if you try to rotate keys? Do the new keys get written to the new default location or the current location?
2. If keys are not found  in `$HOME/.ssh/$USERNAME` then `config` could check whether keys exist in `$HOME/.ssh` and, if so, return an error explaining to the user that they must move their keys to the new location. This has the advantage in that there is only ever one default location, and that the user is made aware when that default changes, and that the user is always in manual control of their key files. The downside to this is that a user's Upspin installation becomes broken until their move their keys. 
3. As with 2, but `config` could do the move itself, transparent to the user. This is user friendly in that it doesn't require the user to do anything, but it is also unfriendly in that it is moving a user's most sensitive data around without telling them.

WDYT all?

**Comment by robpike** [comment]
I agree that we should not store keys in $HOME/upspin by default but (in Unix at least) $HOME/.ssh, a directory that is less likely to leak to the public.

I also agree that the default should be to create a directory under .ssh for each Upspin user.

InitConfig could complain about keys in the old .ssh location. That would encourage people to migrate to the new default. So that's option 1, with logging. 2 and 3 scare me.

**Comment by adg** [comment]
What is it about option 2 that scares you?

**Comment by robpike** [comment]
There are tools such as upspinfs where errors are hard to see, lost in log files. That's a big part of it.

**Comment by rwcarlsen** [comment]
I think sufficient warning to mailing lists and option 2 would be the best FWIW.  I don't want anything moving my keys around, and I also wouldn't want upspin trying to be smart without my knowledge - possibly leading to surprising behavior like @adg mentioned w.r.t. key rotation.

**Comment by adg** [comment]
> There are tools such as upspinfs where errors are hard to see, lost in log files. That's a big part of it.

I apologize if I was not clear, but option 2 proposes that `config.InitConfig` should return an error if the secrets are in the old place. That would mean that upspinfs or any other program that reads a config would error out immediately if the secret is in the old place. The error message would likely be the first and last thing printed by any config-reading program prints before exiting. Does your objection still hold?

**Comment by n2vi** [comment]
$HOME/.ssh/$USERNAME/ is what I'm currently doing myself, and Option 2
seems ok to me.

But I expect to support family members who have never heard of ssh.  On
Windows, I imagine the solution for them will be something like Key Storage
Providers (
https://msdn.microsoft.com/en-us/library/windows/desktop/bb204778(v=vs.85).aspx
)

How about a variant of Option 2 that requires an explicit "secrets:" line
in the config file and, if missing, errors out with a useful suggestion on
what to change?  That error code path could look around for common
locations such as $HOME/.ssh or KSPs that appear to hold relevant keys.

I admit that I've sometimes been an advocate in the past for eliding lines
in config that are the default.  But since we're proposing changing the
default and anticipate a larger change on coming platforms, I argue that
this default is not a good archival value.

**Comment by adg** [comment]
In this case, we are actually using the default for something good: if the user doesn't have a `secrets:` line in their config then we know they just accepted the default. Now, as we migrate to a new default, we can reliably inform them that the default has changed.

If we had already required a `secrets:` line then it would be impossible for us to know whether the user had deliberately put their keys in `$HOME/.ssh` or just accepted the default.

I'm not sure how important this is.

**Comment by robpike** [comment]
OK, option 2 seems ok if you error out at init time.

**Comment by adg** [comment]
Turns out that `signup` always writes a `secrets:` line so very few people will be impacted by this change.
