### ISSUE TITLE
cloud/https: allow serving insecure HTTP on non-loopback addresses

### ISSUE THREAD

**Issue by mikkeloscar** [upspin/upspin#448]
Hello,

Is there a reason why `upspinserver` enforces serving HTTP only on loopback addresses?

https://github.com/upspin/upspin/blob/f27fcc7305bc135078874f5b2d7708daef4b200c/cloud/https/https.go#L164-L166

I assume it's a safety measure of some sort, but I believe it should be possible to serve on non-loopback addresses if desired.

My use case is running `upspinserver` in Kubernetes where I terminate TLS in an ingress proxy (I'm using [traefik](https://traefik.io/) for this, but it's just a detail), and then forward traffic with HTTP to the pods running upspin. For this to work upspinserver must listen on a non-local address in the container, such that it can receive traffic over the pod network.

**Comment by adg** [comment]
As you guessed, it's for safety. We don't want people to run Upspin servers that serve unencrypted HTTP, as it significantly compromises the overall security of the system.

Your use case makes sense, though, and we should make things easier for you. Perhaps merely passing the flag `-insecure` is enough of a cue that most users will think carefully about it beforehand. (We could print an alarming log message when you listen to HTTP on a non-loopback address.)

However, there is one other approach you might consider: use a self-signed TLS cert for the upspinserver, and configuring your traefik to expect that certificate. I ask this because I wonder whether it is significantly more difficult than just serving HTTP, and would prefer to keep the loopback/HTTP restriction in place if it's not too hard. What do you think?

**Comment by mikkeloscar** [comment]
> Your use case makes sense, though, and we should make things easier for you. Perhaps merely passing the flag -insecure is enough of a cue that most users will think carefully about it beforehand. (We could print an alarming log message when you listen to HTTP on a non-loopback address.)

This makes most sense to me, I would say that `-insecure` should be enough of a cue, but a warning message on top wouldn't hurt.

> However, there is one other approach you might consider: use a self-signed TLS cert for the upspinserver, and configuring your traefik to expect that certificate. I ask this because I wonder whether it is significantly more difficult than just serving HTTP, and would prefer to keep the loopback/HTTP restriction in place if it's not too hard. What do you think?

This sounds like configuration overhead which I would like to avoid. In my setup I would also not consider it a huge improvement in terms of security, because if I can't trust the connection between traefik and the pod (which in my case is actually running on the same node), then I would also not trust that no-one tampered with either the traefik server or upspinserver.

**Comment by adg** [comment]
I'm happy to prepare a change to lift the localhost restriction, unless you wish to do so @mikkeloscar. Let me know.

**Comment by mikkeloscar** [comment]
> I'm happy to prepare a change to lift the localhost restriction, unless you wish to do so @mikkeloscar. Let me know.

Actually I would like to do it, also as an opportunity to use gerrit as a review tool, which I never tried before, if you don't mind :)

**Comment by adg** [comment]
@mikkeloscar thanks! Always a pleasure to welcome new contributors. 😄
