### ISSUE TITLE
Listing directory contents is slow with upspinfs

### ISSUE THREAD

**Issue by kaervin** [upspin/upspin#543]
Listing directory contents of a directory with around 100 files is very slow with upspinfs.
Using FUSE/upspinfs listing such a directory takes around 6 seconds.
In comparison, simply using the upspin executable with it's 'ls' command, listing the directory contents of the same directory doesn't even take a single second. 
This is without the cacheserver running. Enabling the cacheserver fixes the problem,
but still I wonder why upspinfs (without the cacheserver) is so comparatively slow.
I am using Ubuntu Linux 16.04 with the 22 Nov build of upspin, using bash to list directories with ls.

**Comment by presotto** [comment]
The fault is that upspinfs doesn't keep anything cached that the kernel/FUSE does not explicitly keep a reference open for whereas cacheserver does.  An ls of a directory with 100 entries results in  300+ rpcs from FUSE to upspinfs about 100 requiring upspinfs to talk to the backend.

I could make upspinfs faster by importing the directory part of the cacheserver into it but, since it is easy enough to just run the cacheserver, I haven't bothered.
