### ISSUE TITLE
cmd/upspinfs: git clone fails with EEXIST

### ISSUE THREAD

**Issue by masiulaniec** [upspin/upspin#552]
I've updated my `upspinfs`+`cacheserver`+`upspinserver-aws` to the latest version. I'm now getting the following error:

```
$ git clone https://github.com/upspin/aws.git
Cloning into 'aws'...
error: could not lock config file .../aws/.git/config: File exists
fatal: could not set 'core.logallrefupdates' to 'true'
$ 
```

(The `...` in `.../aws/.git/config` is my edit of git's output.)

I ran git under strace and searched for the EEXIST errno (aka "File exists"):

```
rename(".../aws/.git/config.lock", ".../aws/.git/config") = 0
open(".../aws/.git/config.lock", O_RDWR|O_CREAT|O_EXCL|O_LARGEFILE|O_CLOEXEC, 0666) = -1 EEXIST (File exists)
```

So `upspinfs` is falsely reporting existence of `config.lock`, an entry that stopped existing a moment before due to a rename.

**Comment by presotto** [comment]
Jasek was kind enough to send me cacheserver and upspinfs logs since I couldn't recreate it on GCE.  The problem is the timeliness of Watch Events.  While Watch events guarantee eventual consistency, they do cause unintended inconsistency if delayed.  The following scenario was what he was seeing:

We have no rename so it gets turned into a Put(config) followed by a Delete(config.lock).  Cacheserver acted on these immediately but then it saw the following Watch stream:

2017/12/04 05:23:40.837054 dir/dircache: Watch("mlnc@mlnc.me/") entry: mlnc@mlnc.me/t/test42/.git/config.lock (delete=false)
2017/12/04 05:23:40.837140 dir/dircache: Watch("mlnc@mlnc.me/") entry: mlnc@mlnc.me/t/test42/.git/config (delete=false)

which recreates config.lock in its mind's eye

after which point git checks to see if config.lock still exists (which cacheserver believes is true)

followed some time later by

2017/12/04 05:23:41.030101 dir/dircache: Watch("mlnc@mlnc.me/") entry: mlnc@mlnc.me/t/test42/.git/config.lock (delete=true)

indicating that the config.lock really has been removed.

My fault entirely.  I need to ignore Watches that are reflecting what has been done by this machine in the past (or any machine if we have more up to date knowledge).  I'm surprised this is the first time it came up.  It probably did but was not easily repeatable. I guess the stream from the AWS server is delayed more than what we normally see on GCE so that it because repeatable and obvious.

Working on a CL to fix the immediate problem.  I may eventually need to return a sequence number from Delete to completely fix it.
