### ISSUE TITLE
Sharing individual files

### ISSUE THREAD

**Issue by derekchiang** [upspin/upspin#562]
As it is, Upspin doesn't allow for sharing individual files.  If a user wants to share a single file, it has to be placed into its own directory first, and then the directory can be shared.

For instance, I have a number of photos in a directory.  I would like to share a single photo with a certain friend, but I do not want them to see all my photos.  There's currently no way to achieve this.

It would be nice to have a way to share individual files.  The only downside I can see is that it would complicate the syntax of the `Access` file.  What are the core maintainers' thoughts on this?

**Comment by adg** [comment]
Even though the Upspin ecosystem is still small, I don't think we should change the access control mechanism at this stage. Implementing the current semantics is already difficult enough. (I've done it a few times now)

Since copies inside Upspin space are essentially free, another way to share specific files with specific people is to create a directory for that person and then 'upspin cp' the file there. It makes a logical copy of the file, but the underlying storage is the same, so the copy only uses a tiny amount of space (the size of the directory entry). IIUC this is how jn.gl does sharing of individual files between users (is that right @transitorykris?).

Since this has come up a couple of times, I will update the FAQ with this suggestion.

**Comment by derekchiang** [comment]
@adg thanks for the prompt response.  The solution you proposed makes sense, but has a number of drawbacks:

* It only works for sharing read access.  If I want someone to modify a file, then I'd have to remember to `cp` the modified copy back to my original tree, which seems cumbersome.
* If I want to delete the file (and make sure that it's not accessible to anyone anymore), I'd have to remember to delete all the copies too.

**Comment by adg** [comment]
@derekchiang this is true, but there are always tradeoffs in designing anything. Directory-based Access restrictions give us general clarity and simplicity, at the expense of specific use cases like this.

**Comment by derekchiang** [comment]
@adg that's true, but I guess what I'm trying to figure out is whether the core team is fundamentally opposed to having per-file access control (e.g. to keep the system simple), or if you just don't have the time to do it.  In other words, if I submit a PR that adds this feature, would you consider accepting it?

With that in mind, here is the new `Access` file format that I have in mind.  I'm curious what you think: (disregard the comments starting with `#`):

```
# The first section is exactly the same as what we have today.
# It applies to the whole directory and subdirectories.
# Thus, all existing Access files will remain valid.

all: family
list: ann@example.com, bob@example.com

# From here, one can start new sections that apply to specific files.
# Each section begins with the name of the file.

photo.jpg
read, write: ann@example.com

document.txt
read, write: family, bob@example.com
```

Obviously, actually implementing support for per-file access control can be quite hard, but I'm just curious if you like the format itself.

**Comment by adg** [comment]
I can't speak for the team as a whole, but IMO this is probably not worth the additional complexity.

As for your proposed Access file design, my main concern is them becoming long and difficult to work with. A directory with thousands of files with different permissions could easily lead to a situation where no human can reasonably comprehend an Access file's contents. That strikes me a worse situation (in terms of accidental sharing) than what you can get with the copying workaround I mentioned.

**Comment by derekchiang** [comment]
I think being able to share a single file is very important though.  Every single popular cloud storage solution supports it.  It's hard to imagine the average user switching to Upspin if there isn't a straightforward way to share a single file.

As for the `Access` file format, I think your concern is valid.  However, the complexity is not something we force on the user.  The `Access` file only gets complicated if the user does have a complicated need to share many individual files with many different users, in which case we are enabling them to do what they want.

We could also have a command like `upspin pack-access`, which would pack an `Access` file into a minimal, canonical form (by removing duplicated rules, for instance).

@robpike @presotto @n2vi any thoughts on this issue?

**Comment by robpike** [comment]
I think that's a very complex thing to implement and test. The way to solve your problem, which I admit isn't ideal, is not prohibitive and is now documented in the FAQ: Make a directory and upspin cp the file there.

I might consider a way to automate that with a helper in the upspin command, a variant of cp that creates a directory and puts the files and an Access file there allowing certain users. However, by the time it's specified with flags and so on, it's probably easier just to do it by hand with file editing. That's part of the idea behind file-based rather than metadata-based access control.

**Comment by n2vi** [comment]
I'd be inclined to mv the file to a subdirectory with expanded Access and leave behind a link so old pathnames still work.  I fear the copy-on-write semantics of cp will bite me for shared editing, though they would be ok for read-only sharing.   All this sounds clumsy but feasible for use on occasion.

I'd like to get more experience with how often this comes up before forming a strong opinion.  For example, maybe a photo is better off as a directory with EXIF metadata in a separate file one can directly text edit, and Lightroom-type changes also in a separate file.  Our inherited Access would work fine then.

Wearing my security hat, my primary concern is not making access so complicated or awkward that major breaches like Alteryx and Uber keep happening.  I'm not certain that we have the right design, but if not one probably should try a different design from scratch rather than embellish ours.  I'm convinced it is worth living with ours for a while and learning as much as possible before trying a redesign.

**Comment by derekchiang** [comment]
@robpike agreed.  Automating the `cp` approach doesn't seem to make sense.

@n2vi I actually like your solution a lot.  The only downside is that you still have to remember to remove the folder if you wanna remove the file, but at least sharing write access works, and you can't accidentally wind up with two copies of the same file with different access rules.

I'm inclined to think that this is a much better approach than using `cp`.  @adg perhaps this should be the approach we recommend in the FAQ?

**Comment by adg** [comment]
@derekchiang I'm not sure. What I put in the FAQ is something I've actually done, and seen done by others. What @n2vi proposed is more fiddly and is also not something that I've ever seen done. I'm hesitant to recommend a workflow that hasn't really been tried by anyone. If you give it a try and find it works for you, then I'm happy to amend the FAQ entry.
