### ISSUE TITLE
cmd/upspinfs: efficient seeking reads

### ISSUE THREAD

**Issue by idrarig** [upspin/upspin#575]
In general, it seems to me that even if I want the head or tail of a big file, all of it must be locally downloaded, not just the beginning. If I upload a 2-gig video to Upspin, I would like to be able to view it somewhere else without downloading 2 gigs, and maybe seek etc. I wonder if this will be feasible in the future.

**Comment by adg** [comment]
Seeking reads in large files is tenable but we'd need to change the `upspin.BlockUnpacker` API to do it. We'd also perhaps consider changing the encryption mechanism to enable this. It's decidedly non-trivial. cc @n2vi

**Comment by n2vi** [comment]
Wasn't that the point of SeekBlock()?   That is, the client verifies some checksums, then is able to seek to the nearest megabyte boundary and does not have to read all 2 gigs.   You were the author, so obviously I'm not telling you anything new, only exhibiting that I don't understand the question.

**Comment by idrarig** [comment]
Interesting, it sounds like the client is already able to seek efficiently. I don't know if this helps, but the behavior I was observing is via upspinfs. Suppose I issue the command `head big-file` where the big file is not cached locally yet. Then the process goes in uninterruptible sleep (I suppose the read blocks as all blocks are fetched over the network). Once it's locally cached, calling head or tail on the big file
takes around 7 seconds (this one's a 400 MB file).

**Comment by n2vi** [comment]
Yes, as best I recall upspinfs+cacheserver operate at the file level.  @presotto would know for sure.

I take blame for pushing toward the whole file design.  In the large-RAM computers I'm used to today, it seemed a reasonable simplification.  I'd prefer a world with directories of 50MB files instead of single 2GB files.  But that's not the application world we live in today, and fortunately the rest of the upspin team has been working to support the more general case.

**Comment by adg** [comment]
Oh, I totally forgot that I did that work. Oops.

**Comment by adg** [comment]
Renaming this as it's an upspinfs-specific thing.

**Comment by presotto** [comment]
A reasonable request.  cacheserver already just caches the 1MB bits you read but upspinfs reads in and saves the whole file as soon as you touch it.  I should be able to easily change that to just the blocks you read/write.  A bit harder to do partial blocks since we use chain encryption but doing jus the 1MB bits should be a big win.  It does throw a wrench into my plans to cache for offline access but not enough to not do it.

**Comment by idrarig** [comment]
@presotto Thanks a million.
