### ISSUE TITLE
Scenario where resend verification email does not work on signup

### ISSUE THREAD

**Issue by sevan** [upspin/upspin#585]
If you happen to use an email address that is not active at the time you try to sign up for an upspin account, sendgrid will not attempt to deliver to that address a second time after the initial bounce. Even though the issue is resolved on the user side and the address is then working.

**Comment by n2vi** [comment]
Good point;  we only meant to lock the email address after successful registration.

I never studied that part of the code enough to know offhand what's wrong, but am assigning myself this issue.

**Comment by n2vi** [comment]
from https://sendgrid.com/docs/Glossary/bounces.html
"A hard bounce might occur because the domain name doesn’t exist or because the recipient is unknown. If a email is on the bounce list, we will auto drop any future requests to this email address."

So indeed what you experienced is understood and not easily fixed from our end.  I can administratively unblock a particular email address if you like, but that's not a great long term solution.  If you want to do it in this instance, contact me directly and we'll discuss.

As I understand it, doing this manual repair via the SendGrid dashboard is safe because we're only protecting against DoS attacks, not against hijacking of actual established user accounts.  (If anyone believes otherwise, please re-open this issue!)
