### ISSUE TITLE
What happened to the upspin mailing list?

### ISSUE THREAD

**Issue by atlaskerr** [upspin/upspin#623]
https://groups.google.com/forum/#!forum/upspin

Was the mailing list deleted?

**Comment by n2vi** [comment]
Not as far as I know, just quiet.   Were you having a specific problem, either with the list or with upspin?

**Comment by wgrr** [comment]
On Fri Aug 23, 2019 at 2:47 PM Eric Grosse wrote:
> Not as far as I know, just quiet.   Were you having a specific problem, either with the list or with upspin?

Apparently upspin google group is currently "private", i could only
open that link if i'm logged in with a subscribed account, even for
looking at list archives.

**Comment by n2vi** [comment]
I'm not the primary administrator of the Group, so will wait for someone else to post the authoritative response.  I do see a Google Groups header saying that groups settings have changed, so conceivably there was an unintended side effect of a global Groups change.  As far as I know, our intent was merely to have a moderated group so that we can have civility in today's unfortunate age of bad behavior on the net.  But we're very welcoming of new users.

If the issue is really about the downsides of subscription, i.e. having to create at least a pseudonymous account, then that's worth a larger discussion in the upspin context.  I do accept primary blame for upspin's security design and in particular the intentionally stronger protection of content than of metadata.  That could be seen as a controversial choice, so I'm happy to explain more.

**Comment by wgrr** [comment]
On Fri Aug 23, 2019 at 7:22 PM Eric Grosse wrote:
> If the issue is really about the downsides of subscription, i.e. having to create at least a pseudonymous account

In my experience, nobody can subscribe with or without an account,
unless an authrorized manually send an invite.

**Comment by adg** [comment]
Somehow the privacy settings changed. Is it working for you now?

**Comment by wgrr** [comment]
On Mon, Sep 2, 2019 at 2:31 AM Andrew Gerrand <notifications@github.com> wrote:
>
> Somehow the privacy settings changed. Is it working for you now?
It looks right to me.
