### ISSUE TITLE
cloud/storage/gcp: objects in bucket are public accessible

### ISSUE THREAD

**Issue by palmamartin** [upspin/upspin#628]
Just created a new upspin installation on google cloud which uses `gcp` as backend storage. I noticed that the objects created by upspin are all public accessible via link. 

![Screenshot 2019-11-27 at 14 28 44](https://user-images.githubusercontent.com/381/69727446-d9459e00-1122-11ea-8fdf-3736732776dc.png)

Is that by design or did I something wrong during setup? For setup I used the steps described in [doc/server_setup_gcp.md](https://upspin.io/doc/server_setup_gcp.md)

**Comment by n2vi** [comment]
That is by design, and is safe because the objects are strongly encrypted by default.

Another way of thinking of it is that in our threat model the cloud storage provider is not trusted, so the protections need to be so good you can let your adversaries have the encrypted blocks. We hope our mathematics is well founded.
