### ISSUE TITLE
client/file: TestFileSeek is slow

### ISSUE THREAD

**Issue by n2vi** [upspin/upspin#654]
client/all_test.go TestFileSeek is very slow.

It may have an infinite loop at "for written[offset]" because there is no "len(written) != Max" test inside the whence loop. But even  ignoring that, I'm having a hard time proving to myself that the algorithm is efficient. For sure it is timing out at 10 minutes on several test machines.

**Comment by rschio** [comment]
Yes, both `for write[offset]` and `for read[offset]` are infinite loops depending on the output (from rand.Intn).

Interestingly, this was probably only found now in Go 1.20 because math.Rand changed, before 1.20 math.Rand was seeded with `rand.Seed(1)`. I tested it with `GODEBUG=randautoseed=0 go test -v` and the tests passed.
